spring:
  application:
    name: robot
  datasource:
    username: mihail
    password: postgres
    url: jdbc:postgresql://localhost:5432/robot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB


save_path: ${SAVING_DIR:fds}


server:
  port: ${PORT:8081}
