spring:
  application:
    name: robot
  datasource:
    username: dasha_diplom_ry1n_user
    password: 10tV3NUrsF1dQVXusVJbNb5CnrnQRCCd
    url: jdbc:postgresql://dpg-d1a5u13e5dus73e9l12g-a:5432/dasha_diplom_ry1n
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB


save_path: ${SAVING_DIR}


server:
  port: ${PORT:8081}
